version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - 8080
    networks:
      - front-end
      - back-end
    depends_on:
      mysql:
        condition: service_healthy 

  docs:
    build:
      context: .
      dockerfile: docs.Dockerfile
    ports:
      - "45001:45001"
    networks:
    - front-end


  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./src/main/webapp:/static
    depends_on:
      - app
    ports:
      - '80:80'
      - '8081:8081'
    networks:
      - front-end
      


  mysql:
    image: mysql:5.7
    volumes:
      - data:/var/lib/mysql
      - ./datadump:/docker-entrypoint-initdb.d
    networks:
      - back-end
    environment:
      - MYSQL_ROOT_PASSWORD=12345
   
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '-uroot', '-p12345']
      interval: 5s
      timeout: 10s
      retries: 10 

networks:
  front-end:
  back-end:

volumes:
  data: