version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile.multistage
    depends_on:
      - elastic-search
    networks:
      - front-end
      - back-end
    ports:
      - "5000:5000"


  elastic-search:
    image: elasticsearch:7.17.0
    hostname: es
    environment:
      - discovery.type=single-node
    networks:
      - back-end
        

  nginx:
    build:
      context: foodtrucks/project/flask-app/nginx/
      dockerfile: Dockerfile
    depends_on:
      - app
    ports:
      - "80:80"
    networks:
      - front-end
    volumes:
      - ./foodtrucks/project/flask-app/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./foodtrucks/project/flask-app/static:/static:ro
      - ./foodtrucks/project/flask-app/templates:/templates:ro
    

networks:
  front-end:
    driver: bridge
  back-end:
    driver: bridge
