version: '3.8'
services:
  flask-app:
      build:
        context: ./app
        dockerfile: Dockerfile
      volumes:
        - ./app/rooms:/app/rooms
      ports:
        - "5000"
      depends_on:
        - db
      restart: on-failure

  nginx:
      image: nginx
      volumes:
        - ./nginx.conf/nginx.conf:/etc/nginx/nginx.conf:ro
      depends_on:
        - flask-app
      ports:
        - "80:80"
  
  db:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=chatLogs
    volumes:
      - data:/var/lib/mysql
    ports:
      - "33012:3306"

volumes:
  data: