CREATE DATABASE IF NOT EXISTS chatLogs;
USE chatLogs;

CREATE TABLE IF NOT EXISTS chat (
  id INT AUTO_INCREMENT PRIMARY KEY,
  room VARCHAR(200) NOT NULL,
  logged VARCHAR(50) NOT NULL,
  username VARCHAR(255) NOT NULL,
  messages VARCHAR(500) NOT NULL
);
