version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./rooms:/app/rooms
    # ports:
    #   - "5000:5000"
    depends_on:
      - db
    restart: on-failure

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app

  db:
    build:
      context: ./Data
      dockerfile: Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DB=chatlogs
    volumes:
      - data:/var/lib/mysql 
    ports:
      - "33012:3306"

volumes:
  data:
